<?php

$calendar_data = array
(
    array("Name" => "1st Gen: Okaeri!",
            "Date" => "9/4/2014",
            "Time" => "7 PM",
            "Location" => "242 Dwinelle",
            "Headline" => "Come join us for our First General Meeting of the year as we welcome you home and into our family!",
            "Description" => "Learn what NSU is all about, participate in a relay race, and enjoy a performance from our a cappella group, The Nikkei Choral Ensemble (NiCE).",
            "Description2" => "Check out the Facebook <a style='color: blue;' href='https://www.facebook.com/events/788920031160907/?ref=25'>Event! </a>"
    ),

array("Name" => "Welcome Picnic!",
            "Date" => "9/6/2014",
            "Time" => "11 AM - 3PM",
            "Location" => "VLSB Lawn",
            "Headline" => "Kick off the semester at NSU's Welcome Picnic! ",
            "Description" => "Join us for an afternoon of food and games. This is a great opportunity to meet your fellow members and NSU's Core. Stop by anytime from 11am to 3pm. Heads up, there is a chance you might get wet!",
            "Description2" => "We'll have lots of fun outdoor activities such as icebreakers, soccer/football, ultimate frisbee/capture the flag, learning an Obon dance (in case you didn't get a chance to check out the Obon Festivals over the summer!), and much more! Heads up, there is a chance you might get wet! Check it out on <a style='color: blue;' href='https://www.facebook.com/events/1466631983614793/?ref=2'>Facebook</a>"
        ),

array("Name" => "Big C Hike w/ Tasa!",
            "Date" => "9/8/2014",
            "Time" => "5:40 PM - 6:30 PM",
            "Location" => "Sproul Plaza -> Foothill Parking Lot",
            "Headline" => "Come out and enjoy a beginning of the year hike with NSU and TASA! ",
            "Description" => "We will meet at 5:40 at the Sproul fountain. If you can't meet there, you can meet at the Foothill parking lot at 6 for some bonding time and hiking! You can email michael_handa@berkeley.edu for more questions."
        ),

array("Name" => "Cheeseboard and a Movie!",
            "Date" => "9/13/2014",
            "Time" => "3:30 PM",
            "Location" => "Meet at Sather Gate, and we will walk to Cheeseboard together",
            "Headline" => "CHEESEBOARD? Did some one say CHEESEBOARD!? ",
            "Description" => "The Cheese Board Collective serves gourmet vegetarian pizza, but fear not my fellow meatatarians this pizza ain't no joke. The fresh ingredients that adorn the gooey cheese-covered crust will make you a believer.",
            "Description2" => "And after you've had your fill of delicious pizza, come join us for a movie! We will walk to Michael Handa's house after dinner for the movie. Don't miss out on a legendary pizza/movie combo!"
        ),
array("Name" => "Osaka University: World Cafe!",
            "Date" => "9/19/2014",
            "Time" => "5 PM - 7 PM",
            "Location" => "30 Wheeler",
            "Headline" => "Meet with students from Osaka University at our World Cafe event! ",
            "Description" => "At the World Cafe, we will be exploring the differences and similarities between Japanese and American culture in work, family, love, education to name a few things. Come out for a unique experience meeting these exchange students from Japan! You don't have to speak Japanese to participate! Contact michael_handa@berkeley.edu for more information.",
            "Description2" => "<a class='red' href='https://www.facebook.com/events/1379857515637610/?ref=25'>Facebook Link Here!</a>"
        ),
array("Name" => "JCCCNC Annual Event!",
            "Date" => "9/20/2014",
            "Time" => "12:40PM - 8:30PM",
            "Location" => "Downtown Berkeley Bart -> JCCCNC, 1840 Sutter Street",
            "Headline" => "Meet at Downtown Berkeley Bart Station at 12:40 pm by top of the escalators!",
            "Description" => "What about networking with leaders in the JA community? Or just hanging out with NSU and the rest of the JA bay area community? Then you should volunteer at Tabemasho with NSU! Tabemasho is the JCCCNC’s (Japanese Cultural and Community Center of Northern California) largest fundraising event of the year.",
            "Description2" => "Every year Tabemasho has 200 volunteers, so the JCCCNC could really use our help. It will take place at the JCCCNC in SF Japan Town on September 20th 4:00pm – 8:00pm. (Please reserve 3:00pm – 10:00pm for commute time). NSU will travel together via Bart and Bus (38) so you won’t have to travel on your own. The Bart and Bus ticket will be given to you by an NSU core member. If you are interested please contact Tara Umemoto at taraumemoto@berkeley.edu ASAP.  "
        ),
array("Name" => "The Amazing Japantown Race!",
            "Date" => "10/4/2014",
            "Time" => "1:00 - 5:30 PM",
            "Location" => "JCCCNC, 1840 Sutter Street",
            "Headline" => "<a style='color: blue;' href='http://www.bit.ly/japantownrace'>Tickets! </a>",
            "Description" => " The Amazing Japantown Race is a fast-paced and fun competition in which teams of four compete against each other in challenges across San Francisco Japantown! Participants will compete for prizes while experiencing J-town's thriving community and culture. To conclude the event, a fundraising dinner and awards ceremony will be held at a local restaurant.",
            "Description2" => "Registration for individuals is $20 and groups of four is $60.  Everyone ages 18 and over is welcome to register and compete. If you have questions regarding volunteering, staffing, or even just participating in the Amazing Japantown Race, call the Japanese Cultural & Community Center of Northern California at (415) 567-5505 or contact Elena at intern3@jcccnc.org."
        ),
array("Name" => "NSU Yosakoi Workshop!",
            "Date" => "9/10/2014",
            "Time" => "5:00 PM - 7:00 PM",
            "Location" => "Meet Sproul Steps -> Zellerbach Playhouse",
            "Headline" => "Contact: ucbnsuyosakoi@gmail.com / John Okahata – (818)282-0854",
            "Description" => "Interested in flailing your arms in a traditional and yet still modern fashion? No? How about making friends while flailing your arms in a traditional and yet still modern fashion? If so, come join Yosakoi! Yosakoi is an energetic Japanese dance that draws inspiration from ocean waves. We perform at NSU's own Culture Show, as well as the annual Cherry Blossom Festival in Japantown. We practice for just 2 hours a week! No dance experience is necessary!"
        ),
array("Name" => "Culture Show!",
            "Date" => "12/6/2014",
            "Time" => "12 PM - 2:15 PM",
            "Location" => "Anna Head Alumnae Hall",
            "Headline" => "Come one, come all to NSU's annual Culture Show! ",
            "Description" => "Enjoy a comedic and dramatic storytelling, coupled with performances from student groups such as Raijin Taiko and Yosakoi. Better yet, bring your friends with you! Even better yet, join the Culture Show cast as an actor, prop designer, or any other role you can think of! Please contact Allen Zhou if you have any questions/concerns. (@allenxzhou@berkeley.edu)",
            "Description2" => "<a class='red' href='https://www.facebook.com/events/1560020804232613/?sid_reminder=1266361426369314816'>Facebook Link Here!</a>"
        ),
array("Name" => "Mini General Meeting!",
            "Date" => "9/18/2014",
            "Time" => "8 PM - 9 PM",
            "Location" => "151 Barrows",
            "Headline" => "Hey Everyone! We're having a quick meeting to catch up and announce some things!",
            "Description" => "It'll basically be another meeting where we will discuss upcoming events, play icebreakers, get to know each other better, and probably go get food or boba together afterwards! Anyone is welcome to come, and we always accept new members  If you haven't been able to come out to some of our events so far, this is a great opportunity to check out what we have to offer! Hope to see you there! ",
            "Description2" => "<a class='red' href='https://www.facebook.com/events/283799261828439/?ref=25'>Facebook Link Here!</a>"
        ),

array("Name" => "Ici's Social!",
            "Date" => "9/27/2014",
            "Time" => "3:30 PM",
            "Location" => "Sather Gate -> Ici Ice Cream",
            "Headline" => "I SCREAM YOU SCREAM WE ALL SCREAM FOR ICE CREAM",
            "Description" => "Come join NSU in this “chill” social event ;) (winky face emoticon). We will be meeting at 3:30 at Sather Gate and will be taking the bus to Ici’s. Please don’t forget your bus pass/student ID! 
",
            "Description2" => "PS if you live on southside and you know how to get there you can just meet the group at 4 pm at Ici's. <a class='red' href='https://www.facebook.com/events/726155317466602/?ref=2&ref_dashboard_filter=upcoming'>Facebook Link Here!</a>"
        ),
array("Name" => "SACBC Bingo Volunteering",
            "Date" => "10/17/2014",
            "Time" => "3:30 and 4:30 (2 Shifts)",
            "Location" => "Southern Alameda County Buddhist Church",
            "Headline" => "Please let Greg know by this Friday, October 10th if you are willing to help out! 
Feel free to email/text him (greg.hori8@gmail.com / 408-828-6613) or stop by our table on Sproul with any questions or to let us know you'll be there!",
            "Description" => "If you think you know Bingo, you've got something coming. It's more than just a game. It's a whirlwind of emotions, chance, and luck. Some people go home hundreds (even thousands) of dollars richer, while others return with empty wallets.",
            "Description2" => "That being said, come help NSU volunteer at Southern Alameda County Buddhist Church's (SACBC) Bingo Night! SACBC generously donates to NSU in exchange for volunteering, so this is a major fundraiser for us and we would greatly appreciate your help."
        ),
array("Name" => "2nd Mini General Meeting: Japanese Snacks!",
            "Date" => "10/2/2014",
            "Time" => "8 pm - 9 pm",
            "Location" => "151 Barrows",
            "Headline" => ":)",
            "Description" => ""
        ),
array("Name" => "CBA Conference",
            "Date" => "10/5/2014",
            "Time" => "11:30 AM",
            "Location" => "TBD",
            "Headline" => "",
            "Description" => ""
        ),
array("Name" => "Cherry Blossom Queen Program Info Session",
            "Date" => "10/7/2014",
            "Time" => "7pm - 8pm",
            "Location" => "186 Barrows",
            "Headline" => "",
            "Description" => "Interested in becoming a Cherry Blossom Princess? Or do you want to hear more information about the Cherry Blossom Queen Program? Then come out to the Cherry Blossom Program info session, tonight (Tuesday, October 7) at 7pm in 186 Barrows! You don't have to participate in the program to come to the info session. The program is a great opportunity to get involved in the Japanese American community and to potentially become the face of the community!"
        ),
array("Name" => "Nichi Bei's 5th Anniversary Celebration!",
            "Date" => "10/12/2014",
            "Time" => "12:35 - 6pm",
            "Location" => "JCCCNC in Japantown",
            "Headline" => "",
            "Description" => ""
        ),
array("Name" => "3rd Mini gen",
            "Date" => "10/16/2014",
            "Time" => "8 PM - 9 PM",
            "Location" => "151 Barrows",
            "Headline" => ":3",
            "Description" => "",
            "Description2" => "<a class='red' href='https://www.facebook.com/events/277662732431904/?ref_dashboard_filter=upcoming'>Facebook Link Here!</a>"
        ),
array("Name" => "Corn Maze!",
            "Date" => "10/25/2014",
            "Time" => "Meet 11:45 AM",
            "Location" => "TBD",
            "Headline" => "",
            "Description" => ""
        ),
array("Name" => "Pumpkins and a Movie!",
            "Date" => "10/31/2014",
            "Time" => "7 PM - 10 PM",
            "Location" => "225 Wheeler",
            "Headline" => "Need Halloween plans? Come out to decorate pumpkins and watch an event!",
            "Description" => "<a class='red' href='https://www.facebook.com/events/1560020804232613/?sid_reminder=1266361426369314816'>Facebook Link Here!</a>"
        ),
array("Name" => "4rth Mini gen",
            "Date" => "11/6/2014",
            "Time" => "8 PM - 9 PM",
            "Location" => "151 Barrows",
            "Headline" => ":3",
            "Description" => "",
            "Description2" => "<a class='red' href='https://www.facebook.com/events/800286623363965/?ref=25&sid_reminder=6872696999364263936'>Facebook Link!</a>"
        ),
array("Name" => "J-Sei Volunteering: Mailing Party",
            "Date" => "11/12/2014",
            "Time" => "5:30 PM - 8:30 PM",
            "Location" => "Berkeley Methodist United Church 1710 Carleton Street",
            "Headline" => "",
            "Description" => ""
        ),
array("Name" => "Berkeley Project!",
            "Date" => "11/8/2014",
            "Time" => "8AM - 4PM",
            "Location" => "Meet at Sproul!",
            "Headline" => "Here is a great opportunity to do some volunteer work fellow NSU’ers AND CJC’ers! The Berkeley Project is a huge one day event where thousands of students unite to help out the Berkeley community.  If you participate you also get lunch and a free T-shirt! So sign up now! **YOU MUST SIGN UP INDIVIDUALLY!!** ",
            "Description" => "How to sign up!
                Go to https://berkeleyproject.org/accounts/register/.
                Either make an account or sign in if you already have one
                In the “Accommodations” section and under “Group” put “CJC-NSU” so you can volunteer with us!"
        ),
array("Name" => "Bowling",
            "Date" => "11/14/2014",
            "Time" => "TBD",
            "Location" => "TBD",
            "Headline" => "",
        ),
array("Name" => "Culture Show All-Cast",
            "Date" => "10/19/2014",
            "Time" => "9am - 1pm",
            "Location" => "Hearst Gym",
            "Headline" => "Hey Culture Show Participants!",
            "Description" => "We will be having an All-Cast to bond together and go through the show together!"
        ),
array("Name" => "Culture Show All-Cast",
            "Date" => "10/26/2014",
            "Time" => "9am - 1pm",
            "Location" => "Hearst Gym",
            "Headline" => "Hey Culture Show Participants!",
            "Description" => "We will be having an All-Cast to bond together and go through the show together!"
        ),
array("Name" => "Culture Show All-Cast",
            "Date" => "11/9/2014",
            "Time" => "9am - 1pm",
            "Location" => "Hearst Gym",
            "Headline" => "Hey Culture Show Participants!",
            "Description" => "We will be having an All-Cast to bond together and go through the show together!"
        ),
array("Name" => "Culture Show All-Cast",
            "Date" => "11/16/2014",
            "Time" => "9am - 1pm",
            "Location" => "Hearst Gym",
            "Headline" => "Hey Culture Show Participants!",
            "Description" => "We will be having an All-Cast to bond together and go through the show together!"
        ),
array("Name" => "Culture Show Tech Rehearsal!",
            "Date" => "11/22/2014",
            "Time" => "9am - 1pm",
            "Location" => "Anna Head",
            "Headline" => "Hey Culture Show Participants!",
            "Description" => "Today will be teach rehearsal so we hope to see everyone there!"
        ),
array("Name" => "1st General Meeting: Oshogatsu!",
            "Date" => "1/28/2015",
            "Time" => "7:30 PM",
            "Location" => "Wheeler 30",
            "Headline" => "Come out and make friends!",
            "Description" => "We'll be learning a little bit about Japanese New Years, watch performances and do some fun activities :)",
            "Description2" => "<a class='red' href='https://www.facebook.com/events/911390742245113/?ref=2&ref_dashboard_filter=upcoming'>Facebook Link!</a>"
        ),
array("Name" => "Kickoff Social!",
            "Date" => "1/31/2015",
            "Time" => "4:30 PM",
            "Location" => "Zachary's Pizzeria",
            "Headline" => "Come out and eat some pizza!",
            "Description" => "Meet at 5 PM at Zachary's or Meet at 4:30 PM at the topside of Underhill to take the 4:49 bus to Zachary's! ",
        ),
array("Name" => "Yosakoi Workshop",
            "Date" => "2/2/2015",
            "Time" => "6:00 PM",
            "Location" => "Zellerbach Playhouse",
            "Headline" => "Check out Yosakoi!",
            "Description" => "We'll be learning part of the semester dance :D. We are meeting at Zellerbach Playhouse, across from Haas Pavillion!"
        ),
array("Name" => "Fenton's",
            "Date" => "2/14/2015",
            "Time" => "TBD",
            "Location" => "",
            "Headline" => "Information soon",
            "Description" => ""
        ),
array("Name" => "Day of Remembrance",
            "Date" => "2/19/2015",
            "Time" => "7 PM",
            "Location" => "Multicutural Center",
            "Headline" => "Information soon",
            "Description" => ""
        ),
array("Name" => "J-Sei Crab Feed",
            "Date" => "2/22/2015",
            "Time" => "4:45 PM",
            "Location" => "BART Station",
            "Headline" => "Volunteering Event",
            "Description" => ""
        ),
array("Name" => "Ice Skating",
            "Date" => "2/28/2015",
            "Time" => "2 PM At BART Station",
            "Location" => "Yerba Buena",
            "Headline" => "Information soon",
            "Description" => ""
        ),
array("Name" => "IJAC",
            "Date" => "4/4/2015",
            "Time" => "Rides will be coordinated",
            "Location" => "UC Davis",
            "Headline" => "An Intercollegiate Conference for Japanese American clubs",
            "Description" => "Please RSVP with Greg Hori at greg.hori8@gmail.com"
        ),
array("Name" => "Ski Trip!",
            "Date" => "3/13/2015",
            "Time" => "ALLLLL WEEKEND",
            "Location" => "LAKE TAHOE!",
            "Headline" => "",
            "Description" => "<a style='color: blue;' href='https://www.facebook.com/events/758740164203660'>Check out the Facebook Event! </a>"
        ),
array("Name" => "Karaoke Social!",
            "Date" => "3/7/2015",
            "Time" => "9:30 PM",
            "Location" => "Jaguar Karaoke on Durant",
            "Headline" => "Sing your heart out!",
            "Description" => "<a style='color: blue;' href='https://www.facebook.com/events/896623610388993'>Check out the Facebook Event! </a>"
        ),
array("Name" => "Senior Video Recordings",
            "Date" => "3/7/2015",
            "Time" => "11 AM - 4 PM",
            "Location" => "TBA on FB",
            "Headline" => "Record messages for our graduating seniors!",
            "Description" => "<a style='color: blue;' href='https://www.facebook.com/events/1561392704150316'>Check out the Facebook Event! </a>"
        ),
array("Name" => "Undoukai! 4th Mini Gen!",
            "Date" => "4/10/2015",
            "Time" => "4PM",
            "Location" => "Memorial Glade",
            "facebook_link" => "https://www.facebook.com/events/845965668808757/",
            "Headline" => "Come out have fun :)!",
            "Description" => ""
        ),
array("Name" => "'Honor and Sacrifice' Showing",
            "Date" => "4/11/2015",
            "Time" => "12 PM",
            "Location" => "101 Wheeler",
            "facebook_link" => "https://www.facebook.com/events/1595688730668577/",
            "Headline" => "",
            "Description" => ""
        ),
array("Name" => "NSU Goes to Cherry Blossom Festival!",
            "Date" => "4/18/2015",
            "Time" => "11:45 AM",
            "Location" => "Bart -> Japantown",
            "facebook_link" => "https://www.facebook.com/events/804514889604148/",
            "Headline" => "",
            "Description" => ""
        ),
array("Name" => "End-of-Year Banquet 2015",
            "Date" => "5/4/2015",
            "Time" => "5:30 PM - 9:00 PM",
            "Location" => "Berkeley Buddhist Temple",
            "facebook_link" => "https://www.facebook.com/events/1621823721372871/",
            "Headline" => "",
            "Description" => ""
        ),
array("Name" => "Omatsuri",
            "Date" => "4/24/2015",
            "Time" => "11:00 AM - 3:00 PM",
            "Location" => "Sproul Plaza",
            "facebook_link" => "",
            "Headline" => "",
            "Description" => ""
        ),
array("Name" => "Taiko Workshop",
            "Date" => "4/25/2015",
            "Time" => "TBA",
            "Location" => "TBA",
            "facebook_link" => "",
            "Headline" => "",
            "Description" => ""
        ),
array("Name" => "1st General Meeting: Pokemon Bunkasai",
            "Date" => "9/3/2015",
            "Time" => "7:00 PM - 9:00 PM",
            "Location" => "220 Wheeler",
            "facebook_link" => "https://www.facebook.com/events/1005668386144952/",
            "Headline" => "",
            "Description" => "Want to find out more about the Nikkei Student Union? We are the Japanese-American group on campus and we invite you all to join us for our 1st General Meeting! Come and find out more about who we are, see some performances and do some Pokemon related activities! We have groups that sing, dance, and volunteer for the community! No need to be Japanese, we accept everyone!"
        ),
array("Name" => "Welcome Picnic",
            "Date" => "9/5/2015",
            "Time" => "1:00 PM - 4:00 PM",
            "Location" => "Meet at Memorial Glade walking to West Circle! ",
            "facebook_link" => "https://www.facebook.com/events/172778233056736/",
            "Headline" => "We are meeting at Memorial Glade and walking to West Circle!",
            "Description" => "Hey NSU! What better way to start off the new semester with a picnic! We’ll be gathering in Memorial Glade to throw some frisbees, have some pizza and Capri Sun, and maybe even play some card games while we’re at it! Not your thing? No worries! You can just chill and talk with us, maybe even read a book or two. Check out the weather before heading out, Berkeley weather can be unpredictable sometimes!"
        ),
array("Name" => "Yosakoi Dance Workshop and How to Join the team!",
            "Date" => "9/9/2015",
            "Time" => "6:00 PM - 8:00 PM",
            "Location" => "Meet in Front of Zellerbach Hall (from there we will walk to Zellerbach Playhouse, where the workshop will take place)",
            "facebook_link" => "",
            "Headline" => "Contact: ucbnsuyosakoi@gmail.com",
            "Description" => "Interested in flailing your arms in a traditional and yet still modern fashion? No? How about making friends while flailing your arms in a traditional and yet still modern fashion? If so, come check out our introductory Yosakoi workshop! Yosakoi is an energetic Japanese dance that draws inspiration from ocean waves. If you end up liking it, you can join NSU’s Yosakoi dance team! We perform at NSU's own Culture Show, Cherry Blossom Festival in Japantown, and other outside performances within the Japanese-American community. We practice for just 2 hours a week, and no dance experience is necessary! We’ll teach you everything you need to know, so if you’ve always wanted to be on a dance team, now is your chance!
<br>
<br>
<b>Workshop details</b>: We’ll meet at 6pm in front of Zellerbach Hall, and walk to Zellerbach Playhouse (near the Alumni House and Haas Pavilion) at 6:10. If you get lost, you can contact Alyssa at 805-284-2392. After the workshop, we’ll get food or boba together in order to get to know each other more!
<br>
<br>
If you cannot make the workshop but are still interested in joining Yosakoi or wondering what it is, check out NSU Yosakoi’s webpage (<a style='color: blue;' href='http://nsu.berkeley.edu/pages/Yosakoi.php'>http://nsu.berkeley.edu/pages/Yosakoi.php</a>) or send us an email at <span style='color: blue;'>ucbnsuyosakoi@gmail.com</span>!"
        ),
array("Name" => "Tabemashou Lunch",
            "Date" => "9/19/2015",
            "Time" => "11:30 AM - 12:40 PM",
            "Location" => "Sliver by Bart",
            "facebook_link" => "",
            "Headline" => "",
            "Description" => "Come out and have lunch with us before we go on to Tabemashou! We'll be trying out the Berkeley favorite Sliver :)"
        ),
array("Name" => "JCCCNC Annual Event [Tabemashou!]",
            "Date" => "9/19/2015",
            "Time" => "2:00 PM - 8:30 PM",
            "Location" => "JCCCNC Japantown",
            "facebook_link" => "",
            "Headline" => "",
            "Description" => "We’re looking for volunteers for one of our biggest volunteer events of the school year, JCCCNC’s Annual Event, also known as Tabemasho! The event goes from 2-8:30pm but we will be meeting at the Downtown Berkeley BART station at around 12:30. All transportation costs and food will be provided for you. The dress is business casual which means a white top and black pants (think server’s outfits). It’s a really fun event full of food serving and just connecting to other NSU members! We would really appreciate everyone coming to help, if you’re interested contact Kelly Hamamoto at khamamoto@berkeley.edu."
        ),
array("Name" => "Osaka World Cafe",
            "Date" => "9/16/2015",
            "Time" => "5:00 PM - 7 PM",
            "Location" => "TBD",
            "facebook_link" => "",
            "Headline" => "",
            "Description" => "Meet with students from Osaka University at our World Cafe event! At the World Cafe, we will be exploring the differences and similarities between Japanese and American culture in work, family, love, education to name a few things. Come out for a unique experience meeting these students from Japan! You don't have to speak Japanese to participate!"
        ),
array("Name" => "Berkeley Buddhist Temple Okaerinasai",
            "Date" => "9/12/2015",
            "Time" => "4:00 PM",
            "Location" => "Berkeley Buddhist Temple (2121 Channing Way)",
            "facebook_link" => "https://www.facebook.com/events/1660265824188066/",
            "Headline" => "",
            "Description" => "Join the Berkeley Buddhist Temple for their welcome back social! They will be having a dharma talk with food and fun! It’s a great way to connect with fellow Buddhists in the area and get to know the community better. If you have any questions you can contact CJ or Bradley at <span style='color: blue;'>berkeleysangha.social@gmail.com</span>."
        ),
array("Name" => "Big C Hike with TASA!",
            "Date" => "10/8/2015",
            "Time" => "TBD",
            "Location" => "Big C",
            "facebook_link" => "",
            "Headline" => "",
            "Description" => "TBD"
        ),
array("Name" => "U-Cha Boba Run",
            "Date" => "9/22/2015",
            "Time" => "6PM",
            "Location" => "U-Cha",
            "facebook_link" => "https://www.facebook.com/events/395179407358660/",
            "Headline" => "",
            "Description" => "Do you like BOBA??? Do you like NSU??? Well then you're in luck. U-Cha is hosting a fundraiser for NSU all day on Tuesday 9/22. If you present the cashier with one of our lovely fliers designed by Grace Yeo, then 10% of that purchase will go towards supporting us! Added bonus, if you want to hang out, we will meet at U-Cha @ 6:00pm to grab a drink together! Hope to see you there!"
        ),
array("Name" => "2nd Gen: Game Night",
            "Date" => "9/30/2015",
            "Time" => "TBD",
            "Location" => "TBA",
            "facebook_link" => "",
            "Headline" => "",
            "Description" => ""
        ),
array("Name" => "Cherry Blossom Queen Infosession",
            "Date" => "10/13/2015",
            "Time" => "7 PM",
            "Location" => "Dwinelle 235",
            "facebook_link" => "",
            "Headline" => "",
            "Description" => "Come out and learn more about the Cherry Blossom Queen Program!"
        ),
array("Name" => "NSUxCJC Berkeley Project",
            "Date" => "10/24/2015",
            "Time" => "8 AM - 4 PM",
            "Location" => "TBD",
            "facebook_link" => "https://www.facebook.com/events/527995197356310/",
            "Headline" => "HELLO NSU AND CJC PEOPLE!! This is CJC’s social chair Cozmo and NSU’s community service chair Kelly!!",
            "Description" => "

On OCT 24TH there will be the Berkeley Project Day held every Fall!! Like every year, Nikkei Student Union and Cal Japan Club are going to have a coalition participating in the day long volunteering event. If you’d like to join us, sign up on The Berkeley Project site and don’t forget to include “NSUXCJC” as the group name to ensure that you’ll get to VOLUNTEER (HAVE FUN) WITH US!!! 
You can have fun and give back to the community AT THE SAME TIME!! *gasps There's also BREAKFAST AND LUNCH provided (plus a free shirt)!!! So sign up noooowwwwwww
"
        ),
array("Name" => "NSUxCJC Halloween Event!",
            "Date" => "10/30/2015",
            "Time" => "TBD",
            "Location" => "TBD",
            "facebook_link" => "",
            "Headline" => "",
            "Description" => "TBD"
        ),
array("Name" => "Japantown Scavenger Hunt Social",
            "Date" => "10/17/2015",
            "Time" => "12PM - 5PM",
            "Location" => "Japantown",
            "facebook_link" => "https://www.facebook.com/events/424657767737510/",
            "Headline" => "",
            "Description" => "Come join NSU for a Japantown adventure! On Saturday October 17th, we will meet in front of the Downtown Berkeley Bart @ 12pm and commute together to Japantown. In Japantown, we will get lunch together and then you will get into teams and learn more about Japantown through a photo scavenger hunt! Don’t miss out on a chance to bond with your favorite people!!!

IMPORTANT!!! You must: 

RSVP: kayla.umemoto@berkeley.edu or say you are attending this event
Be in front of Berkeley Bart @ 12 sharp, otherwise we will leave without you
Bring money for lunch and transportation 
($7.80 round trip Bart, $2.25 bus to Japantown, and $2.25 bus to bart *SF buses don’t give change so bring quarters)
If you have any questions, you can e-mail kayla.umemoto@berkeley.edu!"
        ),
array("Name" => "Sansei Live!",
            "Date" => "10/17/2015",
            "Time" => "5 PM - 7 PM",
            "Location" => "Japantown",
            "facebook_link" => "",
            "Headline" => "",
            "Description" => ""
        ),
array("Name" => "JSei Calendar Stuffing!",
            "Date" => "10/27/2015",
            "Time" => "TBD",
            "Location" => "TBD",
            "facebook_link" => "",
            "Headline" => "",
            "Description" => "TBD"
        ),
array("Name" => "JASSxNSU Event!",
            "Date" => "10/18/2015",
            "Time" => "1 PM",
            "Location" => "Berkeley Marina",
            "facebook_link" => "https://www.facebook.com/events/176374412701850/",
            "Headline" => "",
            "Description" => "This Sunday on October 18, come join NSU and UC Davis’ Japanese Club (JASS) for a picnic at the Marina! We will have fun games and FREE pizza, chips, cookies, and fun! This is a great chance to meet new awesome people from another UC as well as hang out with us amazing people!!! You can either commute to the marina:
1) with us @ 12:35 in front of the RSF to catch the 51B
2) take the 51B without us
Hope to see you there!
"
        ),
array("Name" => "Study Tables!",
            "Date" => "10/7/2015",
            "Time" => "11AM - 2PM",
            "Location" => "Barrows 129",
            "facebook_link" => "",
            "Headline" => "Come study with us!",
            "Description" => "Got some time between classes? Want to study but everyone is in MLK? Come on out to our study tables where you can get some quiet study going on (and maybe a little socializing too :)) Drop in whenever you want!"
        ),
array("Name" => "Study Tables!",
            "Date" => "10/14/2015",
            "Time" => "11AM - 2PM",
            "Location" => "Barrows 129",
            "facebook_link" => "",
            "Headline" => "Come study with us!",
            "Description" => "Got some time between classes? Want to study but everyone is in MLK? Come on out to our study tables where you can get some quiet study going on (and maybe a little socializing too :)) Drop in whenever you want!"
        ),
array("Name" => "Study Tables!",
            "Date" => "10/21/2015",
            "Time" => "11AM - 2PM",
            "Location" => "Barrows 129",
            "facebook_link" => "",
            "Headline" => "Come study with us!",
            "Description" => "Got some time between classes? Want to study but everyone is in MLK? Come on out to our study tables where you can get some quiet study going on (and maybe a little socializing too :)) Drop in whenever you want!"
        ),
array("Name" => "Study Tables!",
            "Date" => "10/28/2015",
            "Time" => "11AM - 2PM",
            "Location" => "Barrows 129",
            "facebook_link" => "",
            "Headline" => "Come study with us!",
            "Description" => "Got some time between classes? Want to study but everyone is in MLK? Come on out to our study tables where you can get some quiet study going on (and maybe a little socializing too :)) Drop in whenever you want!"
        ),
array("Name" => "Study Tables!",
            "Date" => "11/4/2015",
            "Time" => "11AM - 2PM",
            "Location" => "Barrows 129",
            "facebook_link" => "",
            "Headline" => "Come study with us!",
            "Description" => "Got some time between classes? Want to study but everyone is in MLK? Come on out to our study tables where you can get some quiet study going on (and maybe a little socializing too :)) Drop in whenever you want!"
        ),
array("Name" => "Study Tables!",
            "Date" => "10/4/2015",
            "Time" => "12PM - 5PM",
            "Location" => "Evans 47 or 2",
            "facebook_link" => "",
            "Headline" => "Come study with us!",
            "Description" => "Library rooms all taken? Want to study but everyone is in MLK? Come on out to our study tables where you can get some quiet study going on (and maybe a little socializing too :)) Drop in whenever you want! We have two reservations so check both rooms"
        ),
array("Name" => "Study Tables!",
            "Date" => "10/11/2015",
            "Time" => "12PM - 5PM",
            "Location" => "Evans 2",
            "facebook_link" => "",
            "Headline" => "Come study with us!",
            "Description" => "Library rooms all taken? Want to study but everyone is in MLK? Come on out to our study tables where you can get some quiet study going on (and maybe a little socializing too :)) Drop in whenever you want!"
        ),
array("Name" => "Study Tables!",
            "Date" => "10/25/2015",
            "Time" => "12PM - 5PM",
            "Location" => "Evans 2",
            "facebook_link" => "",
            "Headline" => "Come study with us!",
            "Description" => "Library rooms all taken? Want to study but everyone is in MLK? Come on out to our study tables where you can get some quiet study going on (and maybe a little socializing too :)) Drop in whenever you want!"
        ),

);

